# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_Home_Screen(object):
    def upload_video(self):
        os.system('python Copy_File.py')
    
    def record_dance(self):
        os.system('python pose_est\pose_est\main.py')

    def compare_dance(self):
        os.system('python pose_est\post_est\catch_pose.py')

    def setupUi(self, Home_Screen):
        Home_Screen.setObjectName("Home_Screen")
        Home_Screen.resize(800, 600)
        Home_Screen.setStyleSheet("font-size: 20px;")
        self.centralwidget = QtWidgets.QWidget(Home_Screen)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        
        self.Upload_video = QtWidgets.QPushButton(self.centralwidget)
        self.Upload_video.setObjectName("Upload_video")
        
        self.Upload_video.clicked.connect(self.upload_video)
        
        self.gridLayout.addWidget(self.Upload_video, 0, 0, 1, 1)
        self.Record_Dance = QtWidgets.QPushButton(self.centralwidget)
        self.Record_Dance.setObjectName("Record_Dance")
        self.gridLayout.addWidget(self.Record_Dance, 0, 1, 1, 1)

        self.Upload_video.clicked.connect(self.record_dance)


        self.Compare_Dance = QtWidgets.QPushButton(self.centralwidget)
        self.Compare_Dance.setObjectName("Compare_Dance")
        self.gridLayout.addWidget(self.Compare_Dance, 1, 0, 1, 2)

        self.Compare_Dance.clicked.connect(self.compare_dance)

        Home_Screen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Home_Screen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 34))
        self.menubar.setObjectName("menubar")
        Home_Screen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Home_Screen)
        self.statusbar.setObjectName("statusbar")
        Home_Screen.setStatusBar(self.statusbar)

        self.retranslateUi(Home_Screen)
        QtCore.QMetaObject.connectSlotsByName(Home_Screen)

    



    def retranslateUi(self, Home_Screen):
        _translate = QtCore.QCoreApplication.translate
        Home_Screen.setWindowTitle(_translate("Home_Screen", "MainWindow"))
        self.Upload_video.setText(_translate("Home_Screen", "Upload Video File to Estimate"))
        self.Record_Dance.setText(_translate("Home_Screen", "Record Your Dance Moves to Score"))
        self.Compare_Dance.setText(_translate("Home_Screen", "Comparing Dance Moves"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home_Screen = QtWidgets.QMainWindow()
    ui = Ui_Home_Screen()
    ui.setupUi(Home_Screen)
    Home_Screen.show()
    sys.exit(app.exec_())
