# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Scoring.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Scoring(object):
    def setupUi(self, Scoring):
        Scoring.setObjectName("Scoring")
        Scoring.resize(400, 300)
        Scoring.setStyleSheet("")
        self.formLayout = QtWidgets.QFormLayout(Scoring)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Scoring)
        self.label.setStyleSheet("font-size: 40px;")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Scoring)
        self.label_2.setStyleSheet("font-size: 20px;")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.line = QtWidgets.QFrame(Scoring)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.line)
        self.label_3 = QtWidgets.QLabel(Scoring)
        self.label_3.setStyleSheet("font-size: 20px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)

        self.retranslateUi(Scoring)
        QtCore.QMetaObject.connectSlotsByName(Scoring)

    def retranslateUi(self, Scoring):
        _translate = QtCore.QCoreApplication.translate
        Scoring.setWindowTitle(_translate("Scoring", "Dialog"))
        self.label.setText(_translate("Scoring", "Congrats"))
        self.label_2.setText(_translate("Scoring", "Your Score is ____"))
        self.label_3.setText(_translate("Scoring", "Your Accuracy is ____"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Scoring = QtWidgets.QDialog()
    ui = Ui_Scoring()
    ui.setupUi(Scoring)
    Scoring.show()
    sys.exit(app.exec_())
